// <auto-generated />
namespace N01522297_PassionProject_ExpiryDateTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class itempantry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itempantry));
        
        string IMigrationMetadata.Id
        {
            get { return "202206011853430_item-pantry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
